### ISSUE TITLE
mesh problem

### ISSUE THREAD

**Issue by yjgao-gfz** [AxiSEMunity/AxiSEM3D#29]
/anaconda3/envs/axisem3d/lib/python3.8/site-packages/pyexodus/core.py", line 959, in _create_variables
    data=[-1] * self._f.dimensions["num_el_blk"],
TypeError: can't multiply sequence by non-int of type 'Dimension'
Hello, is this related to the newest version of python?

**Comment by jbmuir** [comment]
Hi @yjgao-gfz; this bug is related to a change in the h5netcdf module and has been fixed by https://github.com/SalvusHub/pyexodus/pull/11 ; please install the new version of salvusmeshlite from https://gitlab.com/Salvus/SalvusMeshLite

**Comment by yjgao-gfz** [comment]
Thanks, here I updated my pyexodus and then works, the salvus-mesh is the newest, so probably you should remind the new users for this

**Comment by wolfjonathan** [comment]
Hi there, it seems like a similar salvusmeshlite issue exists again for the version from https://gitlab.com/Salvus/SalvusMeshLite, same error message. This error was reproduced on multiple machines. A workaround is to install salvusmeshlite and then replace the h5netcdf module by an earlier version.

**Comment by jbmuir** [comment]
Hi Jonathan; does updating pyexodus resolve the issue without reverting to an earlier version of h5netcdf? It would be better to avoid requiring users to pin to an older unsupported version if at all possible

**Comment by wolfjonathan** [comment]
Hi Jack, thanks for your quick reply. Just checked, updating pyexodus from https://salvushub.github.io/pyexodus/ also does the job. (It would be nice if this issue could be fixed though on the salvusmeshlite end for future users.)

Another error that happened to me on 2 out of 4 machines when running $ python -m salvus_mesh_lite.interface --input_file=input.yaml is the following. Just noting this down here in case someone out there runs into the same issue. If you anyone gets

File "/Users/jw2449/anaconda3/envs/salvustest/lib/python3.7/runpy.py", line 193, in _run_module_as_main 
    "__main__", mod_spec) 
  File "/Users/jw2449/anaconda3/envs/salvustest/lib/python3.7/runpy.py", line 85, in _run_code 
    exec(code, run_globals) 
  File "/Users/jw2449/anaconda3/envs/salvustest/lib/python3.7/site-packages/salvus_mesh_lite/interface/__main__.py", line 17, in <module> 
    main.main() 
  File "/Users/jw2449/anaconda3/envs/salvustest/lib/python3.7/site-packages/salvus_mesh_lite/interface/main.py", line 344, in main 
    inputs = yaml.load(fh.read()) 

this issue is fixed by replacing line 344 in  ... site-packages/salvus_mesh_lite/interface/main.py by 'inputs = yaml.safe_load(fh.read())'

**Comment by jbmuir** [comment]
Thanks, I'm going to close this issue as the original problem seems to have been resolved & hopefully should be fine for new users (if they are installing pyexodus for the first time...). Please note that the new repository for SalvusMeshLite is https://gitlab.com/swp_ethz/public/SalvusMeshLite - if it would be possible to raise an issue there about the yaml input there, it would be very helpful.
