### ISSUE TITLE
A question about gen_crust1.ipynb

### ISSUE THREAD

**Issue by axelwang** [AxiSEMunity/AxiSEM3D#34]
The python notebook `gen_crust1.ipynb` for example 2 has a parameter `N_ELEM_LAYERS = 2`. Later on, in the *structured grid* subsection, we have `grid_r = np.linspace(RADIUS_MOHO, RADIUS_SURFACE, N_ELEM_LAYERS * 10)`. 

I am wondering why do we have `N_ELEM_LAYERS * 10`? Neither the number nor the actual location of these radial points actually correspond to GLL points on each element, so that is apparently not the logic for setting `grid_r`, but I am wondering what is the logic then?

If I increase `N_ELEM_LAYERS`, how should I adjust `grid_r`? Furthermore, if I want to build a model for, e.g., the mantle, do I still need to count the number of vertical elements there (I can't seem to find how S362ANI is built)? Also there we need to deal with transition layers so I am not sure how would that be done.

Thanks!

**Comment by kuangdai** [comment]
The number `N_ELEM_LAYERS * 10` is not import. Sorry, I wasn't making this clear.

In Crust 1.0, we can have 3~6 layers (depneding one whether you include sediments), and they have different thickness. However, AxiSEM3D requires a structure grid for depth. So what we're doing here is using 20 depths (N_ELEM_LAYERS=2) from moho to surface to sample Crust 1.0. You can use `grid_r = np.linspace(RADIUS_MOHO, RADIUS_SURFACE, 100)` to be safer, not problem.

**Comment by kuangdai** [comment]
The mantle model and the crust models won't interact because they do not overlap in space in this example. If they do, the later model will overwrite the previous one.

In `examples/02_3d_crust_S362ANI_regional/input_with_3d_crust/inparam.model.yaml`, under `list_of_3D_models:`, we first have a model called `EMC_S362ANI `, which build the 3D mantle model from IRIS EMC data.
